#!/bin/sh

set -e

while [ $# -gt 1 ]
do
key="$1"

case $key in
    --name)
    NS_NAME="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

if [ -z "$NS_NAME" ]; then
  echo "Usage with $0 ns-name"
  exit 1
fi

echo "Testing if screen ns-${NS_NAME} exists..."
if ! screen -x ns-${NS_NAME} -X number > /dev/null; then
  echo "Session not found!"
  exit 1
fi

echo "Sending Ctrl+C"
screen -x ns-${NS_NAME} -X at "#" stuff "\003"

sleep 1

echo "Sending exit + Enter"
screen -x ns-${NS_NAME} -X at "#" stuff "exit \015"

sleep 1

echo "Check if screen windows terminated successfully..."
if ! screen -x ns-${NS_NAME} -X number > /dev/null; then
  echo "spawn-ns screen session successfully stopped"
  exit 0
fi

echo "Something went wrong?!?"
echo "Kill remaining windows"
screen -x ns-${NS_NAME} -X at "#" kill
exit 1
