#!/usr/bin/env python3

import argparse
import configparser
import os
import sys

parser = argparse.ArgumentParser(description="Wrapper to create command line arguments out of an ini file.")

parser.add_argument('-c', '--conf-file', required=True, type=argparse.FileType('r'))
parser.add_argument('-s', '--section', required=True)
parser.add_argument('prog')

my_args = parser.parse_args()

config = configparser.ConfigParser()

config.read_file(my_args.conf_file)

if not config.has_section(my_args.section):
    print("Failure, the section %s doesn't exist in config file %s" % (my_args.section, my_args.conf_file.name))
    sys.exit(1)

prog_args = [my_args.prog]

for option in config[my_args.section]:
    prog_args.append('--' + option)
    prog_args.append(config[my_args.section][option])

os.execvp(my_args.prog, prog_args)
