#!/bin/sh
# © 2011 Michael Stapelberg (see also: LICENSE)
#
# Overwrites /etc/resolv.conf by bind-mounting a tempfile over it.
#
# Syntax: spawn-ns-overwrite-dns <dns>

[ -z "$1" ] && { echo "No DNS server specified"; exit 1; }

# If any command fails, we are screwed, so exit.
set -e

# Create a temporary directory with the name of our netspace in it.
TMPDIR=$(mktemp -d "/tmp/ns-${NS_NAME}-dns.XXXXXXXXXX")

mkdir -p ${TMPDIR}/netns
mkdir -p ${TMPDIR}/root

# Create a resolv.conf file in there.
echo "nameserver $1" > ${TMPDIR}/netns/resolv.conf

mount -n --bind /etc ${TMPDIR}/root
mount -t aufs -o br=${TMPDIR}/netns=rw:${TMPDIR}/root=ro,udba=reval none /etc

